source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

gem "jekyll", "~> 3.8.5"
gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
  gem "jekyll-archives"
  gem "jekyll-include-cache"
end
